### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by magick93** [contentacms/contenta_jsonapi#210]
Hello

I am trying to install contenta on OpenShift. To do this I use a custom s2i docker image (source-to-image) that is designed for taking a drupal git repository and making a docker image. This image is working successfully for OpenSocial and Lightning drupal distrubutions.

However, when I use this repository as the source, then try to install, the installation fails.

Firstly I tried with drush:
```
drush -y -v site-install --db-url=$DB_VENDOR://$DB_USER:$DB_PASS@$DB_HOST/$DB_DATABASE
```
I also tried the above cmd from the `web` directory.

This failed with:
```
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                   [error]    

```

Then I tried with drupal-console:
```
drupal site:install  standard --langcode="en"  --db-type=$DB_VENDOR --db-host=$DB_HOST  --db-name=$DB_DATABASE --db-user=$DB_USER --db-pass=$DB_PASS --site-name="Drupal 8"  --
site-mail="admin@example.com"  --account-name="admin"  --account-mail="admin@example.com"   --account-pass="p455w0rd" 
```

This failed with:
```
Drupal\Console\Application-&gt;doRun(Object, Object) (Line: 125)                                                                                                                       
Symfony\Component\Console\Application-&gt;run() (Line: 87)                                                                                                                             
require(&#039;/opt/app-root/src/vendor/drupal/console/bin/drupal.php&#039;) (Line: 4)                                                                                                  
</pre>Error: Call to a member function addPsr4() on boolean in /opt/app-root/src/web/core/lib/Drupal/Core/DrupalKernel.php on line 1475 #0 /opt/app-root/src/web/core/lib/Drupal/Core/D
rupalKernel.php(1204): Drupal\Core\DrupalKernel->classLoaderAddMultiplePsr4(Array)                                                                                                     
#1 /opt/app-root/src/web/core/lib/Drupal/Core/DrupalKernel.php(909): Drupal\Core\DrupalKernel->attachSynthetic(Object(Drupal\Core\DependencyInjection\ContainerBuilder))               
#2 /opt/app-root/src/web/core/lib/Drupal/Core/Installer/InstallerKernel.php(18): Drupal\Core\DrupalKernel->initializeContainer()                                                       
#3 /opt/app-root/src/web/core/lib/Drupal/Core/DrupalKernel.php(466): Drupal\Core\Installer\InstallerKernel->initializeContainer()                                                      
#4 /opt/app-root/src/web/core/includes/install.core.inc(418): Drupal\Core\DrupalKernel->boot()                                                                                         
#5 /opt/app-root/src/web/core/includes/install.core.inc(118): install_begin_request(false, Array)                                                                                      
#6 /opt/app-root/src/vendor/drupal/console/src/Command/Site/InstallCommand.php(549): install_drupal(false, Array)                                                                      
#7 /opt/app-root/src/vendor/drupal/console/src/Command/Site/InstallCommand.php(438): Drupal\Console\Command\Site\InstallCommand->runInstaller(Object(Drupal\Console\Core\Style\DrupalSt
yle), Object(Symfony\Component\Console\Input\ArgvInput), Array, 'default')                                                                                                             
#8 /opt/app-root/src/vendor/symfony/console/Command/Command.php(264): Drupal\Console\Command\Site\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sym
fony\Component\Console\Output\ConsoleOutput))                                                                                                                                          
#9 /opt/app-root/src/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Comp
onent\Console\Output\ConsoleOutput))                                                                                                                                                   
#10 /opt/app-root/src/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Site\InstallCommand), Object(Symfo
ny\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                         
#11 /opt/app-root/src/vendor/drupal/console-core/src/Application.php(160): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfo
ny\Component\Console\Output\ConsoleOutput))                                                                                                                                            
#12 /opt/app-root/src/vendor/drupal/console/src/Application.php(71): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component
\Console\Output\ConsoleOutput))                                                                                                                                                        
#13 /opt/app-root/src/vendor/symfony/console/Application.php(125): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Consol
e\Output\ConsoleOutput))                                                                                                                                                               
#14 /opt/app-root/src/vendor/drupal/console/bin/drupal.php(87): Symfony\Component\Console\Application->run()                                                                           
#15 /opt/app-root/src/vendor/drupal/console/bin/drupal(4): require('/opt/app-root/s...')                                                                                               
#16 {main}                                                                                                                                                                             
Error: Call to a member function addPsr4() on boolean in Drupal\Core\DrupalKernel->classLoaderAddMultiplePsr4() (line 1475 of /opt/app-root/src/web/core/lib/Drupal/Core/DrupalKernel.p
hp).    
```

Do you have any suggestions as to what the problem might be?

Thanks

**Comment by e0ipso** [comment]
Please take a look at the install script described in contentacms.org.

I suspect that your problem is that you did not navigate to `cd web/`.

Feel free to re-open if this was not the issue.

**Comment by magick93** [comment]
Yes I did also try to run `drush -y -v site-install --db-url=$DB_VENDOR://$DB_USER:$DB_PASS@$DB_HOST/$DB_DATABASE` from the `web` dir but got the same result.

I also had a look at the install script. I tried also to run `composer run-script install-contenta . ` but it complained about the directory not being empty, so it will not work with our deployment process.

Is it not possible to use drush to install this project?

**Comment by e0ipso** [comment]
Can you post the working directory where you are executing the drush command?

**Comment by e0ipso** [comment]
I am also noticing that you are missing the Contenta_jsonapi profile. It seems you are using standard?

**Comment by magick93** [comment]
> Can you post the working directory where you are executing the drush command?

I have tried from both the `web` and its parent directory to run `drush -y -v site-install --db-url=$DB_VENDOR://$DB_USER:$DB_PASS@$DB_HOST/$DB_DATABASE`

> I am also noticing that you are missing the Contenta_jsonapi profile. It seems you are using standard?

I am pulling this repository, so, yes, Contenta_jsonapi profile is present.

```
sh-4.2$ ls                                                                                                                                                                             
CHANGELOG.md        LICENSE.txt  composer.json  composer.phar  contenta_jsonapi.info.yml  contenta_jsonapi.profile  humans.txt    mkdocs.yml  phpunit.xml  sites  vendor               
CODE_OF_CONDUCT.md  README.md    composer.lock  config         contenta_jsonapi.install   docs                      installer.sh  modules     scripts      tests  web                  
sh-4.2$ pwd                                                                                                                                                                            
/opt/app-root/src       
```

**Comment by magick93** [comment]
Another example, again from the `web` directory:

```
sh-4.2$ drush si contenta_jsonapi  -y -v  --db-url=$DB_VENDOR://$DB_USER:$DB_PASS@$DB_HOST/$DB_DATABASE                                                               
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                   [error]    
The drush command 'si contenta_jsonapi drush site-install' could not be executed.                                                                                           [error]    

```

**Comment by dawehner** [comment]
@magick93 Can you try the drush inside the vendor directory so:

```
cd web
../vendor/bin/drush si contenta_jsonapi ...
```

Maybe this solves the problem?

**Comment by magick93** [comment]
I also tried this in the `vendor` and the `bin` directories and had the same result.

**Comment by dawehner** [comment]
@magick93 sorry for the stupid question ... Did you tried using -vvv, maybe it includes more information

**Comment by magick93** [comment]
Good point - I had forgotten to do that.

```
sh-4.2$ drush -y -v site-install contenta_jsonapi --db-url=$DB_VENDOR://$DB_USER:$DB_PASS@$DB_HOST/$DB_DATABASE -vvv                                                                   
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                   [error]    
The drush command 'site-install contenta_jsonapi' could not be executed.                                                                                                    [error]    
```

**Comment by dawehner** [comment]
What is the reason that you are using the global install drush. Can you
please try ../vendor as in the example above?

**Comment by magick93** [comment]
When I try using the `../vendor` example above I get;

```
sh-4.2$ cd web                                                                                                                                                                         
sh-4.2$ ../vendor/bin/drush -y -v site-install contenta_jsonapi --db-url=$DB_VENDOR://$DB_USER:$DB_PASS@$DB_HOST/$DB_DATABASE                                                          
sh: ../vendor/bin/drush: No such file or directory                                                                                                                                     
sh-4.2$ cd ..                                                                                                                                                                          
sh-4.2$ cd vendor                                                                                                                                                                      
sh-4.2$ ls                                                                                                                                                                             
alchemy       bin              cweagans  dnoegel   easyrdf       guzzlehttp     league       paragonie  skyscanner  stecman      twig    webmozart                                     
asm89         burdamagazinorg  defuse    doctrine  egulias       jakub-onderka  masterminds  psr        squizlabs   symfony      vlucas  zendframework                                 
autoload.php  composer         dflydev   drupal    gabordemooij  lcobucci       nikic        psy        stack       symfony-cmf  webflo                                                
sh-4.2$ cd bin                                                                                                                                                                         
sh-4.2$ ls                                                                                                                                                                             
check-guidelines.sh  drupal  generate-defuse-key  php-parse  phpcbf  phpcs  psysh                                                                                                      

```

**Comment by ymdahi** [comment]
I'm having a similar problem. Ubuntu 16.04, PHP 7.0
I am able to run drush from /web with `../vendor/drush/drush/drush`
I do not have a /vendor/bin folder.

**Comment by broeker** [comment]
For what is worth I am trying to install Contenta on Pantheon using their build tools. Everything seems to spin up nicely until the build tool calls this command:

`drush site-install contenta_jsonapi --yes --account-mail={account-mail} --account-name={account-name} --account-pass={account-pass} --site-mail={site-mail} --site-name={site-name}`

at which point it errors out with the same message above:

Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.

**Comment by stevector** [comment]
Hi @broeker! I'm working on blending Contenta and Pantheon over in 

- https://github.com/pantheon-systems/example-drops-8-composer/pull/128
- https://github.com/pantheon-systems/example-drops-8-composer/pull/93

You should be able to run `terminus build:project:create pantheon-systems/example-drops-8-composer:dev-contenta--take2` and get a working site + github repo + CircleCI config.

**Comment by broeker** [comment]
@stevector awesome to find you here -- the above command ALMOST worked but not quite, I will post the details in pantheon-systems/example-drops-8-composer#128!

**Comment by e0ipso** [comment]
Many things have changed since this was posted. I will tentatively close this. Please request a re-open if necessary.
