### ISSUE TITLE
 (2/4) Installing Contenta CMS for local usage is failing

### ISSUE THREAD

**Issue by tormi** [contentacms/contenta_jsonapi#33]
ReflectionException: Class  does not exist in                        [error]
/var/www/contentacms/web/core/lib/Drupal/Core/Installer/Form/SiteSettingsForm.php:154

Full stack trace:
```
-----------------------------------------------
 (2/4) Installing Contenta CMS for local usage 
-----------------------------------------------
 EXECUTING  /var/www/contentacms/bin/drush si contenta_jsonapi --db-url=sqlite://sites/default/files/.ht.sqlite --account-pass=test -y


You are about to CREATE the 'sites/default/files/.ht.sqlite' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
ReflectionException: Class  does not exist in                        [error]
/var/www/contentacms/web/core/lib/Drupal/Core/Installer/Form/SiteSettingsForm.php:154
Stack trace:
#0
/var/www/contentacms/web/core/lib/Drupal/Core/Installer/Form/SiteSettingsForm.php(154):
ReflectionClass->__construct('')
#1 [internal function]:
Drupal\Core\Installer\Form\SiteSettingsForm->validateForm(Array,
Object(Drupal\Core\Form\FormState))
#2
/var/www/contentacms/web/core/lib/Drupal/Core/Form/FormValidator.php(83):
call_user_func_array(Array, Array)
#3
/var/www/contentacms/web/core/lib/Drupal/Core/Form/FormValidator.php(270):
Drupal\Core\Form\FormValidator->executeValidateHandlers(Array,
Object(Drupal\Core\Form\FormState))
#4
/var/www/contentacms/web/core/lib/Drupal/Core/Form/FormValidator.php(119):
Drupal\Core\Form\FormValidator->doValidateForm(Array,
Object(Drupal\Core\Form\FormState), 'install_setting...')
#5 /var/www/contentacms/web/core/lib/Drupal/Core/Form/FormBuilder.php(571):
Drupal\Core\Form\FormValidator->validateForm('install_setting...',
Array, Object(Drupal\Core\Form\FormState))
#6 /var/www/contentacms/web/core/lib/Drupal/Core/Form/FormBuilder.php(481):
Drupal\Core\Form\FormBuilder->processForm('install_setting...',
Array, Object(Drupal\Core\Form\FormState))
#7 /var/www/contentacms/web/core/includes/install.core.inc(938):
Drupal\Core\Form\FormBuilder->submitForm('Drupal\\Core\\Ins...',
Object(Drupal\Core\Form\FormState))
#8 /var/www/contentacms/web/core/includes/install.core.inc(594):
install_get_form('Drupal\\Core\\Ins...', Array)
#9 /var/www/contentacms/web/core/includes/install.core.inc(550):
install_run_task(Array, Array)
#10 /var/www/contentacms/web/core/includes/install.core.inc(121):
install_run_tasks(Array)
#11 /var/www/contentacms/vendor/drush/drush/includes/drush.inc(726):
install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#12 /var/www/contentacms/vendor/drush/drush/includes/drush.inc(711):
drush_call_user_func_array('install_drupal', Array)
#13
/var/www/contentacms/vendor/drush/drush/commands/core/drupal/site_install.inc(82):
drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#14
/var/www/contentacms/vendor/drush/drush/commands/core/site_install.drush.inc(255):
drush_core_site_install_version('contenta_jsonap...', Array)
#15 /var/www/contentacms/vendor/drush/drush/includes/command.inc(422):
drush_core_site_install('contenta_jsonap...')
#16 /var/www/contentacms/vendor/drush/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#17 /var/www/contentacms/vendor/drush/drush/includes/command.inc(199):
drush_command('contenta_jsonap...')
#18
/var/www/contentacms/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#19 /var/www/contentacms/vendor/drush/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#20 /var/www/contentacms/vendor/drush/drush/drush.php(12): drush_main()
#21 {main}
 ERROR  The Drupal installer failed to install Contenta CMS.
Script scripts/development/build-contenta_jsonapi.sh handling the install-contenta event returned with error code 3
tormi@ASUS-N56VV:/var/www$ 
```

**Comment by dawehner** [comment]
@tormi Is this particular issue solved for you now?

**Comment by frega** [comment]
@tormi please make sure that the sqlite-extension is installed - depending on your evironment there are a variety of ways how this can be done (in debian/ubuntu this `sudo apt-get install php-sqlite3` would do the trick ...) 

#24 addresses the depedency check that would catch this :)

**Comment by tormi** [comment]
Thanks @frega , that did the trick!
