### ISSUE TITLE
Update path from 3.0.666 to 3.0.679 seems to be broken

### ISSUE THREAD

**Issue by IT-Cru** [contentacms/contenta_jsonapi#369]
When I try to update our existing comtenta CMS project from 3.0.666 to 3.0.679 via composer, we get following errors during run of drush updb command:

```
[warning] The following module is missing from the file system: dropzonejs bootstrap.inc:277
 [warning] The following module is missing from the file system: dropzonejs_eb_widget bootstrap.inc:277
 [warning] The following module is missing from the file system: entity_browser bootstrap.inc:277
 [warning] The following module is missing from the file system: entity_browser_entity_form bootstrap.inc:277
 [warning] The following module is missing from the file system: media_entity_browser bootstrap.inc:277
 ------------------- ---------------- --------------- ------------------------- 
  Module              Update ID        Type            Description              
 ------------------- ---------------- --------------- ------------------------- 
  system              8701             hook_update_n   Remove the unused        
                                                       'system.theme.data'      
                                                       from state.              
  system              8702             hook_update_n   Add the                  
                                                       'revision_translation_a  
                                                       ffected' entity key.     
  file                8700             hook_update_n   Set the 'owner' entity   
                                                       key and update the       
                                                       field.                   
  jsonapi             8701             hook_update_n   Enable BC: default the   
                                                       new read-only mode to    
                                                       "off" on existing        
                                                       sites.                   
  media               8700             hook_update_n   Set the 'owner' entity   
                                                       key and update the       
                                                       field.                   
  node                8700             hook_update_n   Set the 'owner' entity   
                                                       key and update the       
                                                       field.                   
  taxonomy            8701             hook_update_n   Add an index on the      
                                                       'taxonomy_term__parent'  
                                                       field table.             
  media               enable_standal   post-update     Keep media items         
                      one_url                          viewable at media{id}.   
  menu_link_content   make_menu_link   post-update     Update custom menu       
                      _content_revis                   links to be              
                      ionable                          revisionable.            
  system              add_expand_all   post-update     Initialize               
                      _items_key_in_                   'expand_all_items'       
                      system_menu_bl                   values to                
                      ock                              system_menu_block.       
  system              clear_menu_cac   post-update     Clear the menu cache.    
                      he                               @see                     
                                                       https:www.drupal.orgpro  
                                                       jectdrupalissues3044364  
  system              fix_jquery_ext   post-update     Clear the library cache  
                      end                              and ensure aggregate     
                                                       files are regenerated.   
  taxonomy            make_taxonomy_   post-update     Update taxonomy terms    
                      term_revisiona                   to be revisionable.      
                      ble                                                       
  taxonomy            remove_hierarc   post-update     Remove the 'hierarchy'   
                      hy_from_vocabu                   property from            
                      laries                           vocabularies.            
  views               exposed_filter   post-update     Update exposed filter    
                      _blocks_label_                   blocks label display to  
                      display                          be disabled.             
  views               make_placehold   post-update     Rebuild cache to allow   
                      ers_translatab                   placeholder texts to be  
                      le                               translatable.            
 ------------------- ---------------- --------------- ------------------------- 
 // Do you wish to run the specified pending updates?: yes.                     
 [warning] The following module is missing from the file system: dropzonejs bootstrap.inc:277
 [warning] The following module is missing from the file system: dropzonejs_eb_widget bootstrap.inc:277
 [warning] The following module is missing from the file system: entity_browser bootstrap.inc:277
 [warning] The following module is missing from the file system: entity_browser_entity_form bootstrap.inc:277
 [warning] The following module is missing from the file system: media_entity_browser bootstrap.inc:277
>  [notice] Update started: system_update_8701
>  [notice] Update completed: system_update_8701
>  [notice] Update started: system_update_8702
>  [notice] Update completed: system_update_8702
>  [notice] Update started: file_update_8700
>  [notice] Update completed: file_update_8700
>  [notice] Update started: jsonapi_update_8701
>  [notice] Update completed: jsonapi_update_8701
>  [notice] Update started: media_update_8700
>  [notice] Update completed: media_update_8700
>  [notice] Update started: node_update_8700
>  [notice] Update completed: node_update_8700
>  [notice] Update started: taxonomy_update_8701
>  [notice] Update completed: taxonomy_update_8701
>  [notice] Update started: media_post_update_enable_standalone_url
>  [notice] Update completed: media_post_update_enable_standalone_url
>  [notice] Update started: menu_link_content_post_update_make_menu_link_content_revisionable
> [07-May-2019 14:26:16 UTC] TypeError: Argument 1 passed to Drupal\Core\Config\Entity\ConfigEntityBase::calculatePluginDependencies() must implement interface Drupal\Component\Plugin\PluginInspectionInterface, null given, called in /var/www/html/docroot/core/modules/views/src/Entity/View.php on line 291 in /var/www/html/docroot/core/lib/Drupal/Core/Plugin/PluginDependencyTrait.php on line 92 #0 /var/www/html/docroot/core/modules/views/src/Entity/View.php(291): Drupal\Core\Config\Entity\ConfigEntityBase->calculatePluginDependencies(NULL)
> #1 /var/www/html/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(319): Drupal\views\Entity\View->calculateDependencies()
> #2 /var/www/html/docroot/core/modules/views/src/Entity/View.php(302): Drupal\Core\Config\Entity\ConfigEntityBase->preSave(Object(Drupal\Core\Config\Entity\ConfigEntityStorage))
> #3 /var/www/html/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(490): Drupal\views\Entity\View->preSave(Object(Drupal\Core\Config\Entity\ConfigEntityStorage))
> #4 /var/www/html/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(445): Drupal\Core\Entity\EntityStorageBase->doPreSave(Object(Drupal\views\Entity\View))
> #5 /var/www/html/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(263): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\views\Entity\View))
> #6 /var/www/html/docroot/core/lib/Drupal/Core/Entity/EntityBase.php(394): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\views\Entity\View))
> #7 /var/www/html/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(613): Drupal\Core\Entity\EntityBase->save()
> #8 /var/www/html/docroot/core/modules/views/src/EventSubscriber/ViewsEntitySchemaSubscriber.php(202): Drupal\Core\Config\Entity\ConfigEntityBase->save()
> #9 /var/www/html/docroot/core/lib/Drupal/Core/Entity/EntityTypeEventSubscriberTrait.php(47): Drupal\views\EventSubscriber\ViewsEntitySchemaSubscriber->onEntityTypeUpdate(Object(Drupal\Core\Entity\ContentEntityType), Object(Drupal\Core\Entity\ContentEntityType))
> #10 [internal function]: Drupal\views\EventSubscriber\ViewsEntitySchemaSubscriber->onEntityTypeEvent(Object(Drupal\Core\Entity\EntityTypeEvent), 'entity_type.def...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
> #11 /var/www/html/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\Core\Entity\EntityTypeEvent), 'entity_type.def...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
> #12 /var/www/html/docroot/core/lib/Drupal/Core/Entity/EntityTypeListener.php(138): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('entity_type.def...', Object(Drupal\Core\Entity\EntityTypeEvent))
> #13 /var/www/html/docroot/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php(229): Drupal\Core\Entity\EntityTypeListener->onFieldableEntityTypeUpdate(Object(Drupal\Core\Entity\ContentEntityType), Object(Drupal\Core\Entity\ContentEntityType), Array, Array, Array)
> #14 /var/www/html/docroot/core/modules/menu_link_content/menu_link_content.post_update.php(100): Drupal\Core\Entity\EntityDefinitionUpdateManager->updateFieldableEntityType(Object(Drupal\Core\Entity\ContentEntityType), Array, Array)
> #15 /var/www/html/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(289): menu_link_content_post_update_make_menu_link_content_revisionable(Array)
> #16 /var/www/html/vendor/drush/drush/includes/batch.inc(251): Drush\Commands\core\UpdateDBCommands::updateDoOnePostUpdate('menu_link_conte...', Object(DrushBatchContext))
> #17 /var/www/html/vendor/drush/drush/includes/batch.inc(196): _drush_batch_worker()
> #18 /var/www/html/vendor/drush/drush/includes/batch.inc(99): _drush_batch_command('124')
> #19 /var/www/html/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(155): drush_batch_command('124')
> #20 [internal function]: Drush\Commands\core\UpdateDBCommands->process('124', Array)
> #21 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
> #22 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #23 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #24 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
> #25 /var/www/html/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #26 /var/www/html/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #27 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #28 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #29 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #30 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
> #31 /var/www/html/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
> #32 /var/www/html/vendor/drush/drush/drush(4): require('/var/www/html/v...')
> #33 {main}
>  [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.
```

I think some before update docs are missing, because of switch from contrib to core modules.

**Comment by e0ipso** [comment]
I see!

Thanks for reporting. This issue is due to the D8.7 upgrade. Please report to the drupal.org/project/drupal issue queue for assistance on this. Likely there will be others with the same issue.
